# Site settings
title: A Review of German Films
email: 
description: > # this means to ignore newlines until "baseurl:"
 Imogen's Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kinddieserzeit.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  kinddieserzeit

# Build settings
markdown: kramdown
